// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TableDataGenerator.PbDataGeneratorSystem
{
    using System.Text;
    using System.Collections.Generic;
    using System.Linq;
    using System;
    using System.Text;
    using System.Collections.Generic;
    using OfficeOpenXml.FormulaParsing.Excel.Functions.Logical;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Repository\FangZhou\FangZhouSolution\TableDataGenerator\PbDataGeneratorSystem\ProtoT4.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ProtoT4 : ProtoT4Base
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 13 "D:\Repository\FangZhou\FangZhouSolution\TableDataGenerator\PbDataGeneratorSystem\ProtoT4.tt"

    var pckName = Session["PckName"] as string ?? throw new Exception("missing PckName");
    //table名应当和excel表文件名大小写一致
            var tableName = Session["TableName"] as string ?? throw new Exception("missing table Name");
            //列名没有要求，但生成的代码总是大写开头的
            var columNames = Session["ColumNames"] as string[] ?? throw new Exception("missing ColumNames");
            //它应该是int32 int64 string double bool中的一种，不应该是其他类型
            var columTypesPrefix = Session["ColumTypes"] as string[] ?? throw new Exception("missing ColumTypes");
            //决定是否添加repeated标识
            var columIsAry = Session["ColumIsAry"] as bool[] ?? throw new Exception("missing ColumIsAry");
            //注释数组不能为null，注释内容可以为空白，自动忽略空白
            var colComment = Session["ColumComment"] as string[] ?? throw new Exception("missing ColumComment");
            // var colTags = Session["ColumTag"] as string[] ?? throw new Exception("missing ColumTag");
            // var filter = Session["Filter"] as string ?? throw new Exception("missing filter");
            var isIncluded = Session["ColumIsIncluded"] as bool[] ?? throw new Exception("missing ColumIsIncluded");
            
            var len = columNames.Length;
            if (columTypesPrefix.Length != len || columIsAry.Length != len || colComment.Length != len)
                throw new Exception("invalid colum");

            
            #line default
            #line hidden
            this.Write("//auto generate\r\nsyntax = \"proto3\";\r\n\r\noption csharp_namespace = \"TableModels.Models\"; \r\n\r\npackage ");
            
            #line 38 "D:\Repository\FangZhou\FangZhouSolution\TableDataGenerator\PbDataGeneratorSystem\ProtoT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pckName));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nmessage ");
            
            #line 40 "D:\Repository\FangZhou\FangZhouSolution\TableDataGenerator\PbDataGeneratorSystem\ProtoT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("Table{\r\n");
            
            #line 41 "D:\Repository\FangZhou\FangZhouSolution\TableDataGenerator\PbDataGeneratorSystem\ProtoT4.tt"

            for (int i = 0; i < columTypesPrefix.Length; i++)
            {
                var prefix = columTypesPrefix[i];
                var isAry = columIsAry[i];
                var name = columNames[i];
                var comment = colComment[i];
                //如果这列的tags包含filter字，则该字段会被生成代码。否则只生成被注释掉的代码
                //第0行是id行，固定会被包含不受tag影响
                //tags.Length==0的情形即此列tag为空白，表示输入任何filter参数都参与生成
                var isInclude = isIncluded[i];

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 53 "D:\Repository\FangZhou\FangZhouSolution\TableDataGenerator\PbDataGeneratorSystem\ProtoT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isInclude?"":"//"));
            
            #line default
            #line hidden
            
            #line 53 "D:\Repository\FangZhou\FangZhouSolution\TableDataGenerator\PbDataGeneratorSystem\ProtoT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((string.IsNullOrWhiteSpace(comment) ? "" : $"//{comment}")));
            
            #line default
            #line hidden
            this.Write("\r\n    ");
            
            #line 54 "D:\Repository\FangZhou\FangZhouSolution\TableDataGenerator\PbDataGeneratorSystem\ProtoT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isInclude?"":"//"));
            
            #line default
            #line hidden
            
            #line 54 "D:\Repository\FangZhou\FangZhouSolution\TableDataGenerator\PbDataGeneratorSystem\ProtoT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isAry ? "repeated " : ""));
            
            #line default
            #line hidden
            
            #line 54 "D:\Repository\FangZhou\FangZhouSolution\TableDataGenerator\PbDataGeneratorSystem\ProtoT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prefix));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 54 "D:\Repository\FangZhou\FangZhouSolution\TableDataGenerator\PbDataGeneratorSystem\ProtoT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 54 "D:\Repository\FangZhou\FangZhouSolution\TableDataGenerator\PbDataGeneratorSystem\ProtoT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i + 1));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 55 "D:\Repository\FangZhou\FangZhouSolution\TableDataGenerator\PbDataGeneratorSystem\ProtoT4.tt"

            }

            
            #line default
            #line hidden
            this.Write("}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class ProtoT4Base
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
