// //note:inject by roslyn
//
// // ReSharper disable once CheckNamespace
// public static partial class EnvironmentConfig
// {
//     public static string Root { get; } = "";
//     public static string Client { get; } = "";
//     public static string Solution { get; } = "";
//     public static string UnityEditorDlls { get; } = "";
// }

public partial class EnvironmentConfig
{
    //some members are generated by roslyn
    public const string ConfigFileName = "workspaceconfig.toml";
    public const string ConfigFullFileName = Root + "/" + ConfigFileName;
}